server:
  port: 8080

spring:
  datasource:
    # Thay đổi thông tin DB của bạn ở đây (hoặc dùng environment variables)
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d5j0ijnpm1nc73fj5cf0-a:5432/airlabs_db}
    #postgresql: //postgresql://postgres1:BSU5bqRa996QgA5Hye5iSKDB2Cd1VMG9@dpg-d5j0ijnpm1nc73fj5cf0-a/airlabs_db
    username: ${SPRING_DATASOURCE_USERNAME:postgres1}
    password: ${SPRING_DATASOURCE_PASSWORD:BSU5bqRa996QgA5Hye5iSKDB2Cd1VMG9}
    # url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    # username: ${SPRING_DATASOURCE_USERNAME:postgres}
    # password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    # Tự động cập nhật schema (tạo bảng/cột mới nếu chưa có)
    hibernate:
      ddl-auto: update  
    
    # Hiển thị câu lệnh SQL trong console để dễ debug
    show-sql: true
    
    # Cấu hình Dialect cho PostgreSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Format SQL cho dễ đọc hơn

airlabs.api:
  base-url: https://airlabs.co/api/v9
  api-key: 1ffd3d4c-1ea9-4b6c-8f0e-2250ad010506

spring.data.redis:
  host: ${SPRING_REDIS_HOST:real-adder-15816.upstash.io}
  port: ${SPRING_REDIS_PORT:6379}
  password: ${SPRING_REDIS_PASSWORD:AT3IAAIncDI5YWUxYzFhODU5OTA0ZjJkOTA5M2RkNjJmNWIwOWMzOXAyMTU4MTY}
  ssl: 
    enabled: true
  timeout: 60000ms
  # Cho phép app khởi động ngay cả khi Redis không kết nối được
  jedis:
    pool:
      max-active: 10
      max-idle: 5
      min-idle: 1
      max-wait: 2000ms

# Disable Redis health check để không bắt buộc phải có Redis
management:
  health:
    redis:
      enabled: false 
