name: airlabs-realtime-flight
on: 
  push:
    branches:
      - QA
      - Production
  
jobs:
  docker: 
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        id: env
        run: |
          if ["{{ github.ref}}" == "ref/heads/QA"]; then
            echo "environment=qa" >> $GITHUB_OUTPUT
            echo "port=8081" >> $GITHUB_OUTPUT
            echo "tag_prefix=qa" >> $GITHUB_OUTPUT
          elif ["{{ github.ref}}" == "ref/heads/Production"]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "port=8080" >> $GITHUB_OUTPUT
            echo "tag_prefix=prod" >> $GITHUB_OUTPUT
          fi
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Cache Docker Image Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.env.outputs.environment }}-${{ github.sha}}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ steps.env.outputs.environment}}-
            ${{ runner.os}}-buildx-

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            hienminh1332004/airlabs-realtime-flight:${{ steps.env.outputs.tag_prefix }}-v0.0.${{ github.run_number }}
            hienminh1332004/airlabs-realtime-flight:${{ steps.env.outputs.tag_prefix }}-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
         
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Wait for image to be available
        run: sleep 10

      - name: Notify server to deploy
        run: |
          curl -X POST http://3.88.65.140:9000/hooks/deploy-airlabs \
            -H "Content-Type: application/json" \
            -d '{
              "image": "hienminh1332004/airlabs-realtime-flight:${{ steps.env.outputs.tag_prefix }}-v0.0.${{ github.run_number }}",
              "environment": "${{ steps.env.outputs.environment }}",
              "port": "${{ steps.env.outputs.port}}"
            }'